FORMAT: 1A

# Да съхраним Българското
An API for this project https://github.com/Stamenov96/DaSuhranimBulgarskoto For more info see the Readme.md file in the repo.

# Group Categories
All categories in the page

## Main Categories [/category]
### List all Main Categories [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Народни Танци"
        }, {
          "id": 2, "title": "Обичаи"
        },{
          "id": 3, "title": "Поверия"
        }]


## Sub Categories [/category/{id}/subcat]
### List all Main Categories [GET]
+ Response 200 (application/json)

        {"page":1,
        "results":
        [{
          "id": 1, "title": "Северняшка област"
        }, {
          "id": 2, "title": "Добруджанска област"
        },{
          "id": 3, "title": "Шопска област"
        },{
          "id": 4, "title": "Пиринска област"
        },{
          "id": 5, "title": "Родопска област"
        },{
          "id": 6, "title": "Тракийска област"
        },{
          "id": 7, "title": "Странджанска област"
        }]},
        {"page":2.
        "results":
        [{
        
        
        }]}





### Remove a Note [DELETE]
+ Response 204
