FORMAT: 1A

# Да съхраним Българското
An API for this project https://github.com/Stamenov96/DaSuhranimBulgarskoto For more info see the Readme.md file in the repo.

# Group Main Categories
Categories in the main page

## Main Categories [/notes]
### List all Main Categories [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Народни Танци"
        }, {
          "id": 2, "title": "Обичаи"
        },{
          "id": 3, "title": "Поверия"
        }]

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
